repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: gofmt -w -s
        language: system
        types: [go]
        files: ^lms/

      - id: goimports
        name: goimports
        entry: goimports -w
        language: system
        types: [go]
        files: ^lms/
        require_serial: true

      - id: go-vet
        name: go-vet
        entry: go -C lms vet ./...
        language: system
        types: [go]
        files: ^lms/
        pass_filenames: false

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
