use auth::{AuthService, CreateStudentCommand, Permission};
use serde::Deserialize;
use topcoat::{
    Result,
    context::{Cx, app_context},
    router::{content::Form, page},
    view::{View, view},
};

use crate::session::require_permission;

#[derive(Debug, Deserialize)]
pub struct CreateStudentForm {
    pub login: String,
}

#[page("/students/new")]
async fn create_student_page(cx: &Cx) -> Result<impl View> {
    let _actor = require_permission(cx, Permission::CreateStudentAccount).await?;

    Ok(view! {
        <section class="mx-auto max-w-md space-y-6">
            <h1 class="text-3xl font-semibold tracking-tight">"Create student"</h1>
            <p class="text-sm text-zinc-600">"Password will be generated by the server."</p>
            <form method="post" action="/students" class="space-y-4 rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
                <label class="block space-y-2 text-sm font-medium text-zinc-700">
                    "Login"
                    <input
                        name="login"
                        required=""
                        autocomplete="off"
                        class="block w-full rounded-md border border-zinc-300 px-3 py-2 text-zinc-900 shadow-sm focus:border-zinc-500 focus:outline-none"
                    />
                </label>
                <button
                    type="submit"
                    class="inline-flex w-full justify-center rounded-md bg-zinc-900 px-4 py-2 text-sm font-medium text-white hover:bg-zinc-700"
                >
                    "Create"
                </button>
            </form>
            <p><a href="/" class="text-sm text-zinc-600 hover:text-zinc-900">"Back"</a></p>
        </section>
    })
}

#[page(POST "/students")]
async fn create_student_form(cx: &Cx, Form(input): Form<CreateStudentForm>) -> Result<impl View> {
    let actor = require_permission(cx, Permission::CreateStudentAccount).await?;
    let auth: &AuthService = app_context(cx);
    let result = auth
        .create_student(
            &actor,
            CreateStudentCommand {
                login: input.login,
                password: None,
            },
        )
        .await
        .map_err(|error| topcoat::Error::msg(error.to_string()))?;

    let temporary_password = result
        .temporary_password
        .unwrap_or_else(|| "(password was supplied)".into());

    Ok(view! {
        <section class="mx-auto max-w-md space-y-6">
            <h1 class="text-3xl font-semibold tracking-tight">"Student created"</h1>
            <div class="space-y-3 rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
                <p class="text-zinc-700">"Login: " <span class="font-medium">(result.login)</span></p>
                <p class="text-zinc-700">
                    "Temporary password: "
                    <code class="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-sm">(temporary_password)</code>
                </p>
                <p class="text-sm text-amber-700">"Copy it now — it will not be shown again."</p>
            </div>
            <div class="flex gap-4 text-sm">
                <a href="/students/new" class="text-zinc-900 underline-offset-4 hover:underline">"Create another"</a>
                <a href="/" class="text-zinc-600 hover:text-zinc-900">"Home"</a>
            </div>
        </section>
    })
}
