brand-title = dino_lms

nav-login = Login
nav-students = Students
nav-lang-en = EN
nav-lang-ru = RU

home-welcome = Welcome
home-signed-in = Signed in as { $user }
home-create-student = Create student
home-log-out = Log out
home-sign-in-prompt = Sign in to manage the LMS.
home-log-in = Log in

login-title = Login
login-label = Login
login-password = Password
login-submit = Sign in
login-redirecting = Signed in. Redirecting…
login-error-invalid = Invalid login or password

student-create-title = Create student
student-create-hint = Password will be generated by the server.
student-login-label = Login
student-create-submit = Create
student-back = Back
student-created-title = Student created
student-created-login-label = Login:
student-created-password-label = Temporary password:
student-created-password-supplied = (password was supplied)
student-created-copy-hint = Copy it now — it will not be shown again.
student-create-another = Create another
student-home = Home

error-unauthenticated = Unauthenticated
error-forbidden = Forbidden
error-invalid-credentials = Invalid login or password
error-session-user-missing = Session user missing
error-generic = Something went wrong
