[package]
edition.workspace = true
license.workspace = true
name = "web"
version.workspace = true

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]
auth.workspace = true
config.workspace = true
courses.workspace = true
db.workspace = true
fluent-templates.workspace = true
futures-util.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
kernel.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
topcoat = { workspace = true, features = ["tailwind"] }

[build-dependencies]
topcoat = { workspace = true, features = ["tailwind"] }
